version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html            
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # fastcgi_pass php-fpm:9000;
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    image: php-fpm #php:8-fpm       
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb-data:/data/db
  mongodb-compass:
    image: mongo-express:latest
    container_name: my-mongodb-compass
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongodb